name: Book Library Room

on:
  schedule:
    - cron: "1 16 * * *"  # Runs at 16:01 UTC daily
  workflow_dispatch:      # Allows manual triggering

jobs:
  book-room:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pyyaml webdriver_manager
    
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Display Chrome and ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version
    
    - name: Run booking script
      env:
        CONFIG: ${{ secrets.CONFIG_YAML }}
      run: |
        # Start the ChromeDriver
        chromedriver --version
        google-chrome --version
        
        # Run your script
        python bookingScript.py
    
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: |
          *.png
          booking_log.txt
