name: Book Library Room

on:
  schedule:
    - cron: "1 16 * * *"  # Note: Fixed the cron syntax (added missing space)
  workflow_dispatch:

jobs:
  book-room:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
      
      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      
      - name: Display Chrome and ChromeDriver versions
        run: |
          google-chrome --version
          chromedriver --version
      
      - name: Create config file and run booking script
        env:
          CONFIG: ${{ secrets.CONFIG_YAML }}
        run: |
          echo "$CONFIG" > config.yaml
          python bookingScript.py
